# Generated by Django 5.2.15 on 2026-06-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.SlugField(help_text="Stable member identifier", unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("home_airport", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "preferred_cabin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium economy"),
                            ("business", "Business"),
                            ("first", "First"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("preferred_carriers", models.JSONField(blank=True, default=list)),
                ("loyalty_programs", models.JSONField(blank=True, default=list)),
                ("avoid_redeyes", models.BooleanField(default=False)),
                ("trips_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["handle"],
            },
        ),
        migrations.CreateModel(
            name="TripRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=4)),
                ("destination", models.CharField(max_length=4)),
                ("carrier_code", models.CharField(max_length=3)),
                (
                    "cabin",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("premium_economy", "Premium economy"),
                            ("business", "Business"),
                            ("first", "First"),
                        ],
                        max_length=20,
                    ),
                ),
                ("booked_with_points", models.BooleanField(default=False)),
                ("on_time", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
